### ISSUE TITLE
На видео из Zoom не хватает подписей

### ISSUE THREAD

**Issue by smith3v** [devops-ru/hangops_ru#2]
Так как нет подписей и мы не представляемся голосом, то совершенно не полнятно кто все эти люди и почему они обо все этом разговаривают. Нужно как-то решить проблему с подписями, либо представляться, когда вступаешь в разговор впервые.

**Comment by mkuzmin** [comment]
А почему вы с Hangouts on Air ушли, из-за лимита в 10 участников?
Помимо подписей там удобно было, что запись сразу сама выкладывается.

**Comment by smith3v** [comment]
Насколько я понимаю, Семен предложил это и решили попробовать. Вроде как качество связи у Zoom  лучше и позволяет подключаться до 50 человек. Да и ноуты легче переносят звонки через Zoom. Однако, появилась проблема с подписями и SPOF из #4 .

В последних встречах было < 10 человек общавшихся активно. Остальные могли бы как раньше смотреть стриминг на YouTube. Я предлагаю откатиться на Hangouts и попробовать его текущую версию. Как минимум, чтобы понять текущее состояние.

**Comment by mkuzmin** [comment]
У меня есть корпоративная подписка на G Suite. Google недавно обещал, что там количество участников увеличено до 25. 

Будет такой же SPOF в другом месте, но с понятным планом Б.

**Comment by smith3v** [comment]
Хотелось бы обойтись совсем без SPOF. Давайте попробуем Hangout on Air еще разок?

**Comment by mkuzmin** [comment]
Я непонятно выразился. 
Если запускать Hangouts on Air не под личным gmail-акаунтом, а под рабочим, то количество участников должно увеличиться с 10 до 25-и.

**Comment by nvkv** [comment]
Может тоже закрыть, раз с зума уехали?
