### ISSUE TITLE
Записи на YouTube заливаются под персональным аккаунтом

### ISSUE THREAD

**Issue by smith3v** [devops-ru/hangops_ru#3]
Нужно найти как завести канал, в который смогут заливать видео разные люди.

**Comment by smith3v** [comment]
YouTube позволяет завести Brand account и управлять им несколькими людьми - https://support.google.com/youtube/answer/1646861?hl=en-GB

Похоже это то, что нужно.

**Comment by knazarov** [comment]
Я сделал бренд. Теперь могу добавлять людей. Пишите сюда свои адреса, я вас добавлю.

**Comment by smith3v** [comment]
Отлично! Добавь меня kuz...v AT gmail.com

**Comment by knazarov** [comment]
@smith3v done

**Comment by Frodox** [comment]
А какой канал то..? Чтобы в доках указать.
Почту в ЛС скинул

**Comment by knazarov** [comment]
@Frodox канал вот: https://www.youtube.com/channel/UCr5mwN4AKxiYxysr8PeQdaA

**Comment by Frodox** [comment]
Хочу заметить, что с SoundCloud  - та же история :)

**Comment by knazarov** [comment]
@Frodox увы, у SoundCloud нет групповых аккаунтов, в отличие от YouTube. Придется пароль передавать.

**Comment by knazarov** [comment]
Короче, я это закрываю, потому что аккаунт на YouTube теперь групповой. Если хотите получить права на заливку - просто пишите мне
