### ISSUE TITLE
Я -- SPOF со своим Zoom аккаунтом

### ISSUE THREAD

**Issue by nvkv** [devops-ru/hangops_ru#4]
Сейчас мы используем для посиделок мой zoom и только я могу включить в нём запись, если когда-нибудь я не смогу присутствовать на посиделках, то придётся срочно выдумывать отходной вариант.

Давайте придумаем его заранее?

**Comment by Frodox** [comment]
Что мешает включить запись на компе любому из участников, а не только тебе "средствами Зума"?

**Comment by nvkv** [comment]
Я палагаю это будет дико неудобно :)

**Comment by Frodox** [comment]
Всего то..?)
А тогда вариантов то не много)

* Использовать другой бесплатный сервис, где есть авто-запись 
* Купить зум/etc на всех

**Comment by smith3v** [comment]
Давайте попробуем провести встречу через Hangouts. Если подойдет, то проблема решится.

**Comment by nvkv** [comment]
Отличная мысль, потому что я скорее всего пропущу следующую посиделку :(

**Comment by aladmit** [comment]
Думаю, это можно закрыть, давно уже зумом не пользуемся
