### ISSUE TITLE
Неточности в wiki для организатора

### ISSUE THREAD

**Issue by Frodox** [devops-ru/hangops_ru#5]
> Создать событие  в гугл-календаре.

чьём..? и дальше нигде нет на него ссылки/указания/использования. И для чего, если календарь есть и в других сервисах (фб, миитап)

> Написать анонс встречи в X

За сколько..?

> Создать событие  в гугл-календаре. Напоминалки должны быть за день до встречи, в день встречи и за час до встречи

А имеет смысл писать анонсы "до выбора темы" ? Т.е. "будет посиделка тогда то". Люди смотрят - ок, и чё, о чём..? Скорее всего имелось ввиду это "после выбора темы", но почему тогда до сих пор никто не изменил порядок?)

**Comment by smith3v** [comment]
>> Создать событие в гугл-календаре.
> чьём..? и дальше нигде нет на него ссылки/указания/использования. И для чего, если календарь есть и в других сервисах (фб, миитап)

Было бы здорово, если можно было добавить событие в календарь прямо из FB. Тогда можно обойтись без лишних сущностей в виде Meetup.com. Пока можно и в личном создать.

>> Написать анонс встречи в X
>За сколько..?

Нет ограничения. Как готов, так и пиши.

> А имеет смысл писать анонсы "до выбора темы" ? Т.е. "будет посиделка тогда то". Люди смотрят - ок, и чё, о чём..? Скорее всего имелось ввиду это "после выбора темы", но почему тогда до сих пор никто не изменил порядок?)

Анонс нужно делать, когда выбрал тему и нашел основных участников. До этого особо анонсировать нечего. Разве только тот факт, что ты вызвался ее организовать.

**Comment by Frodox** [comment]
> Было бы здорово, если можно было добавить событие в календарь прямо из FB.

так можно же
1. Можно добавить 1 выбранное событие в календарь себе. На [странице события](https://www.facebook.com/events/411422042554414/) жмём три точки, экспорт, отправить на почту или сохранить файл. Можно давать [прямой линк на ical](https://www.facebook.com/events/ical/export/?eid=411422042554414) в анонсах, и когда люди будут смотреть с телефона (предполагаю) импортируют к себе в календарь.
2. Каждый пользователь может добавить все события своего фейсбука себе в календарь (в том же окошке есть ниже полный URL на webcal). Тут будут только события, в которых он interested или going. В принципе должно подойти. [Офф.инструкция по экспорту своих событий](https://www.facebook.com/help/152652248136178). Только не ясно, будет ли синхронизироваться

> Тогда можно обойтись без лишних сущностей в виде Meetup.com

Эта сущность для другого) Чтобы напоминать участникам и приглашать их **по почте**. +там людей намного больше, чем в чатике, о котором не все знают.

>  Пока можно и в личном создать.

меня больше смущает, что в фб в группе могут создавтаь эвенты только админы. А как вот организатору создавать? просить админа (какого)? проситься в админы (у кого?). Не сказано

> Анонс нужно делать, когда выбрал тему и нашел основных участников

согласен. Ок, исправлю

**Comment by knazarov** [comment]
@smith3v в OS X можно в настройках интернет аккаунтов поставить галочку на фейсбучных календарях, и тогда события из фейсбука будут попадать в системный календарь
<img width="665" alt="internet_accounts_and_ _ _wiki_ _ _ _issue__5_ _devops-ru_hangops_ru" src="https://cloud.githubusercontent.com/assets/6728841/25303003/8a629c68-2753-11e7-9270-2b6d534cea47.png">

**Comment by smith3v** [comment]
Спасибо @racktear. Себе настрою, попробую.

**Comment by Frodox** [comment]
Вот макаводы собрались, а :D 
А в телефон/планшет добавить ещё, или вы всегда с ноутом сверяетесь?)

**Comment by mkuzmin** [comment]
это неочевидно, но в Facebook есть webcal feed для экспорта в Google Calendar
https://www.facebook.com/help/152652248136178/

**Comment by smith3v** [comment]
> это неочевидно, но в Facebook есть webcal feed для экспорта в Google Calendar
https://www.facebook.com/help/152652248136178/

Спасибо, @mkuzmin ! Я предпочитаю Google Calendar и смог подключить календарь из ФБ в Google по этой инструкции. Добавил оповещения к событиям в календаре. Должно работать и для новых событий.

**Comment by smith3v** [comment]
~~Если прокатит, то можно давать ссылку на событие в FB-календаре.~~
Не, это требует сделать календарь публичным. Не все, наверное, готовы так сделать.

**Comment by soq** [comment]
@smith3v @Frodox Давайте добавим на страницу "Как запустить Hangout on Air" в  пункт "Запускать встречу можно будет по кнопке Start Hangouts On Air" скриншот https://yadi.sk/i/cANVPvLX3HQhhA -- добавим однозначности при нестандартном поведении интерфейса youtube?

Еще очень нужно проапдейтить "Руководство организатора" -- зум больше не используется. 

Но самое главное -- пишем в ФБ и meetup "Ссылка на хангоутс будет за 15 минут", но ссылка прилетает только в слак и в телеграм. Давайте что-то выберем: или везде постим ссылку на hangouts за 15 минут, или убираем эту фразу.

**Comment by smith3v** [comment]
Дал доступ @soq для обновления.

> Давайте что-то выберем: или везде постим ссылку на hangouts за 15 минут, или убираем эту фразу.

Я за формулировку: "Постим ссылку на встречу в slack-канале  HangOps за 5-10 минут до встречи".

**Comment by soq** [comment]
Поапдейтила, что показалось важным. 
Сильно смущает фраза про календарь, которым никто не пользуется, как я понимаю. 
Может, её убрать уже?

**Comment by smith3v** [comment]
Пробовали: но личные календари шарить неудобно? А общий так и не завели. Эту проблему отчасти решает подписка на событие в FB. Я за то, чтобы убрать.

**Comment by Frodox** [comment]
Так, рук пофиксил, остался вопрос с календарём.
В общем плюс гуглового в том, что можно создать те самые напоминания за час, с утра, за день. В fb и т.п. напоминаний нет.

Хотя сегодня вот я расшарил событие в своём гугл.календаре, а у людей что-то не открывается. Давайте голосование что ли устроим, кто как часто пользуется напоминаниями.
если они не нужны, можно прикреплять ссылку на ics из fb/meetup.

**Comment by smith3v** [comment]
> можно прикреплять ссылку на ics из fb/meetup

Вот это бы попробовать. Я не видел как это работает.

**Comment by Frodox** [comment]
в общем пока что создаём событие в своём гугл календаре.
я создал у себя отдельный календарь и сделал его публичным по дефолту и +напоминалки установил. в итоге удобно , нажал "создать событие" и многое уже проставлено.

пока собираю статистику, но как минимум по 15-30 человек используют ссылку на календарь (кликают/переходят).

из fb/meetup можно сохранить файл с событием, но  
* в нём нет напоминаний
* его нужно где-то хостить
* не везде поддерживается/открывается,в  плане с телефона, или с десктопа.. в общем если настроена интеграция на ics, да и то.
