### ISSUE TITLE
Перенести видео из старого канала

### ISSUE THREAD

**Issue by Frodox** [devops-ru/hangops_ru#6]
из [Руслана хэнгопсовича](https://www.youtube.com/channel/UCWPCFdJuC8zNn0loiXFRi2Q) в [новый канал](https://www.youtube.com/channel/UCr5mwN4AKxiYxysr8PeQdaA)

**Comment by smith3v** [comment]
Нашел как сделать. Нужно, чтобы @racktear дал права владельца брендированного канала. После этого смогу перевести все записи.

**Comment by knazarov** [comment]
@smith3v сделал тебя владельцем канала

**Comment by smith3v** [comment]
Не получится перекинуть записи средствами YouTube - может только полностью замещать каналы:

![image](https://cloud.githubusercontent.com/assets/941676/25336098/05b22578-2907-11e7-95e0-1bbb183d46f4.png)

Придется выгружать видео руками и загружать руками в правильный канал. Оно нам точно надо? Долго, а профит не понятен. 

Давайте пока оставим как есть. Новый контент будет идти в новый канал, старый останется где сейчас.
