### ISSUE TITLE
Определиться с форматом приём обратной связи и предложений

### ISSUE THREAD

**Issue by Frodox** [devops-ru/hangops_ru#7]
Первая обратная связь - под видео про [DevOps Days 2017](https://www.youtube.com/watch?v=KWNpgK8ofyk&lc=z13cdd1rxyatengxg04ciljirnvhhpvw05w)

> мне кажется главная задача ...
> Расскажите какие плюсы,минусы ...
> Мои любимые выпуски Ansible,Kanban,Мониторинг сделаны именно в этом ключе.Вот еще мануал от довольно известного подкастера в рунете

Он почти угадал всё..)
* Может, нам открыть гугл-хрень для приёма "предложений" и указывать её под каждым видео? Чтобы случаные люди (нигде не зареганные, которые нашли видео в поиске и т.п.) могли достучаться и дать предложения. 
* Или кому-то мониторить все коменты к видео и выдергивать из них полезные вещи и... заносить в гитхаб-предложения))
* Или надеяться что все найдут "вдруг" слаку и т.п.) 
* Или дать гитхаб как место создания предложений

В любом случае стоит явно указать способ/канал, где мы ожидаем обратную связь

**Comment by mkuzmin** [comment]
еще есть коменты в Disqus, которые тоже не очень живые

**Comment by smith3v** [comment]
@Frodox ты предлагаешь людей загонять в одно место: которое мы сочтём наиболее подходящим. По-моему, это не реально. На каждой странице (Facebook, Youtube, пост на сайте, Twitter) уже есть форма для комментариев. Человек уже может оставить свои мысли. Ему незачем переходить в "специальное место". 

Ну и лишнее действие - это способ уменьшить поток обратной связи. А у нас и так потока нет никакого пока.

Нужно реально обходить все эти каналы и общаться с людьми. Если людям не отвечают, то они больше не пишут. Это ИМХО.

Я бы хотел услышать других мнений.

**Comment by mkuzmin** [comment]
Обходить каналы в поисках комментариев - сложно и медленно. Было бы прикольно найти способ настроить бота, который постил их в наш Slack

**Comment by Frodox** [comment]
@smith3v и да и +к @mkuzmin . Мы же не палкой загоняем)
я предлагаю хотя бы ссыль в описании оставить, что 
> мы рады любой обратной связи по [этой ссылке](). 

Её всё равно будут кидать везде, но так может чуточку уменьшим хаос) Согласен, что стоит сперва начать. Но подумать о будущем же можно?
Бот - тоже идея, но он может только всё подряд постить в заданный канал, и там будет и спам тоже. Но, попробовать можно, согласен

**Comment by Frodox** [comment]
Предлагаю оставлять ссылки на страницу мероприятия fb + ссылку на эту репу gh
+ смотреть комменты по сетям
